feat: coverage tracking
famedly/Meow-Coverage pull request #11
Opened 2023-08-28 10:54 UTC by EliseZeroTwo

This PR implements tracking coverage of multiple projects in a centralised repository.

A small overview of the format can be found here: https://github.com/famedly/coverage-reports/blob/main/Description.md

2023-08-28 10:54 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/signed)](https://cla-assistant.io/famedly/Meow-Coverage?pullRequest=11) <br/>All committers have signed the CLA.

2023-08-29 08:04 UTC, emgrav requested changes
Looks great, two small notes though.

Looking at the whole PR, what are your thoughts on testing meow-coverage itself?

2023-08-29 08:04 UTC, chgrv commented on entrypoint.sh
> +    meow-coverage --github-token $MEOWCOV_GITHUB_TOKEN --repo-name $MEOWCOV_REPO_NAME coverage-run --source-prefix $MEOWCOV_SOURCE_PREFIX --commit-id $MEOWCOV_COMMIT_ID --new-lcov-file $MEOWCOV_NEW_L
Could you add some brief comments to this section explaining the logic? Just something short about the different cases and what the intended result is.

2023-08-29 08:04 UTC, chgrv commented on src/coverage/html.rs
> +fn gather_lines(lines: &[u32]) -> Vec<(u32, u32)> {
A unit test of this function would be good, if nothing else for providing an example of input and expected output for ease of readability.

2023-08-30 06:37 UTC, EliseZeroTwo commented
> Looks great, two small notes though.
> 
> Looking at the whole PR, what are your thoughts on testing meow-coverage itself?

Some of the modules (such as `tracking/models.rs`) could be tested, but a lot of the code is dependent on the GitHub API which is also where most of the issues could come up (They don't specify their APIs well leading to having to assume some undefined behaviors about them, and they have also broke things without documenting them several times that I ran across). For general testing of this repo though I will open an issue because there certainly are places where tests can be added and would be useful.

2023-09-06 08:17 UTC, emgrav approved these changes
Looks good, great job!

As previously discussed more tests would be good, but since there's a plan to add those I think this is ready.

2023-09-06 11:52 UTC, merged